### ISSUE TITLE
🫡🫡🫡

### ISSUE THREAD

**Issue by Anthony-hcy** [DreamHelium/dhlrc#1]
🫡🫡🫡诶嘿

**Comment by DreamHelium** [comment]
我都快要放弃这项目了🥲

**Comment by Anthony-hcy** [comment]
为什么😢



---Original---
From: ***@***.***&gt;
Date: Wed, Jun 19, 2024 00:03 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [DreamHelium/dhlrc] 🫡🫡🫡 (Issue #1)




 
我都快要放弃这项目了🥲

**Comment by DreamHelium** [comment]
没人用啊🥲🥲🥲

**Comment by Anthony-hcy** [comment]
不知道，反正我看不懂你的库是干嘛的，我没学过，我只会用那种插件、软件的库



惜
***@***.***







                       
原始邮件
                       
                     

发件人："孟茎骇"< ***@***.*** &gt;;

发件时间：2024/6/20 16:23

收件人："DreamHelium/dhlrc"< ***@***.*** &gt;;

抄送人："半截诗-github"< ***@***.*** &gt;;"Author"< ***@***.*** &gt;;

主题：Re: [DreamHelium/dhlrc] 🫡🫡🫡 (Issue #1)




 
没人用啊🥲🥲🥲

**Comment by DreamHelium** [comment]
库是另一个，这个是程序，不过说实话现在还是不适合普通用户使用（主要是有的地方太妥协了，需要各种改动）
